apiVersion: v1
kind: ConfigMap
metadata:
  # Ejercicio 4:
  # Este ConfigMap almacenara el contenido del DDL.
  name: ddl-sql
  namespace: database
data:
  # TODO ejercicio 4:
  # Copiar aqui el contenido del DDL trabajado en la practica 2.
  init.sql: |
    -- Completa este bloque con el modelo de datos.
    -- Pista:
    -- - tabla de control healthcheck
    -- - tabla favorite_colors para el backend Python
    CREATE TABLE IF NOT EXISTS healthcheck (
      id SERIAL PRIMARY KEY,
      created_at TIMESTAMP DEFAULT NOW()
    );

    INSERT INTO healthcheck DEFAULT VALUES;

    CREATE TABLE IF NOT EXISTS favorite_colors (
      name VARCHAR(20) PRIMARY KEY,
      color VARCHAR(20)
    );

    INSERT INTO favorite_colors (name, color)
    VALUES
      ('Lancelot', 'blue'),
      ('Galahad', 'yellow')
    ON CONFLICT DO NOTHING;
