apiVersion: v1
kind: Service
metadata:
  name: backend-java-headless
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: backend-java
  ports:
    - name: http
      port: {{ .Values.backendJava.servicePort }}
      targetPort: {{ .Values.backendJava.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-java
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend-java
  ports:
    - name: http
      port: {{ .Values.backendJava.servicePort }}
      targetPort: {{ .Values.backendJava.containerPort }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-python
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend-python
  ports:
    - name: http
      port: {{ .Values.backendPython.servicePort }}
      targetPort: {{ .Values.backendPython.containerPort }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: webui
  ports:
    - name: http
      port: {{ .Values.webui.servicePort }}
      targetPort: {{ .Values.webui.containerPort }}
  type: ClusterIP
