apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.webui.replicaCount }}
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: {{ .Values.webui.image }}
          ports:
            - containerPort: {{ .Values.webui.containerPort }}
